#!/usr/bin/env node
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const publicDir = path.join(__dirname, "public");
const iconsDir = path.join(__dirname, "src-tauri", "icons");

// Copy the main logo as the base icon
fs.copyFileSync(
  path.join(publicDir, "logo.png"),
  path.join(iconsDir, "icon.png")
);

// Copy the 180px logo as close approximations
fs.copyFileSync(
  path.join(publicDir, "logo180.png"),
  path.join(iconsDir, "128x128.png")
);
fs.copyFileSync(
  path.join(publicDir, "logo180.png"),
  path.join(iconsDir, "128x128@2x.png")
);

// For 32x32, we'll use the 180px logo (will be resized by Tauri)
fs.copyFileSync(
  path.join(publicDir, "logo180.png"),
  path.join(iconsDir, "32x32.png")
);

// Copy logo.png as base for all Windows Square logos (ImageMagick will resize them)
const windowsLogos = [
  "Square30x30Logo.png",
  "Square44x44Logo.png",
  "Square71x71Logo.png",
  "Square89x89Logo.png",
  "Square107x107Logo.png",
  "Square142x142Logo.png",
  "Square150x150Logo.png",
  "Square284x284Logo.png",
  "Square310x310Logo.png",
  "StoreLogo.png",
];

// Copy the main logo as base for all Windows logos (will be resized by ImageMagick in CI)
windowsLogos.forEach((logo) => {
  fs.copyFileSync(path.join(publicDir, "logo.png"), path.join(iconsDir, logo));
});

console.log("Icons updated successfully!");
console.log("- icon.png: 512x512 from public/logo.png");
console.log("- 128x128.png: 180x180 from public/logo180.png");
console.log("- 128x128@2x.png: 180x180 from public/logo180.png");
console.log(
  "- 32x32.png: 180x180 from public/logo180.png (will be resized by Tauri)"
);
console.log(
  "- Windows Square logos: All updated with your logo (will be resized by ImageMagick)"
);
console.log("");
console.log(
  "Note: ICO and ICNS files will be generated by Tauri build process from icon.png"
);
