name: Build All Platforms & Deploy

on:
  push:
    branches: ["tauri-migration"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "deploy-all"
  cancel-in-progress: true

jobs:
  build:
    name: Build & Upload All Artifacts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            name: linux
          - target: x86_64-pc-windows-msvc
            name: windows
          - target: android-armv7
            name: android-armeabi-v7a
          - target: aarch64-linux-android
            name: android-arm64-v8a
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: "npm"

      - name: Install Dependencies
        run: npm install

      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Install Tauri CLI
        run: npm install -D @tauri-apps/cli

      - name: Setup Android NDK (for Android targets)
        if: contains(matrix.target, 'android')
        run: |
          sudo apt update && sudo apt install -y unzip curl
          curl -sL https://dl.google.com/android/repository/commandlinetools-linux-13114758_latest.zip -o cmdline-tools.zip
          unzip -q cmdline-tools.zip -d android-sdk
          mkdir -p $HOME/android-sdk/cmdline-tools/latest
          mv android-sdk/cmdline-tools/* $HOME/android-sdk/cmdline-tools/latest/
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH
          yes | sdkmanager --licenses || true
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0" "ndk;27.2.12479018"
          echo "ANDROID_NDK_HOME=$HOME/android-sdk/ndk/27.2.12479018" >> $GITHUB_ENV

      - name: Build Tauri App
        run: npx tauri build --target ${{ matrix.target }}

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}-build
          path: |
            src-tauri/target/${{ matrix.target }}/release/bundle
            !**/*.dSYM

  web:
    name: Build Web & Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build web
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  release:
    name: Release to GitHub
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Zip all builds
        run: |
          cd artifacts
          for dir in *; do
            zip -r "../${dir}.zip" "$dir"
          done

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.sha }}
          tag_name: ${{ github.sha }}
          files: |
            *.zip
